modLoader = "kotlinforforge"
loaderVersion = "[${neoforge_kotlin_version},)"
issueTrackerURL = "${issues_url}"
license = "${license}"

[[mods]]
modId = "${mod_id}"
version = "${version}"
displayName = "${mod_name}"
displayURL = "${homepage_url}"
logoFile = "assets/${mod_id}/icon.png"
authors = "${authors}"
description = "${description}"

[[mixins]]
config = "${mod_id}.mixins.json"
[[mixins]]
config = "${mod_id}-neoforge.mixins.json"

[[dependencies.${mod_id}]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range_neoforge}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "neoforge"
type = "required"
versionRange = "${neoforge_version_range}"
ordering = "NONE"
side = "BOTH"
